public class FirstClass {
    Public static void method1(){
    	integer i;
        long j;
        decimal k;
        String s;
        i = 123;
        j = 1234567890;
        k = i/j;
        s = 'First Test Class';         
        System.debug(s);
        System.debug('Test Class integer '+ i);   
        System.debug('Test Class Long '+ j); 
        System.debug('Test Class Long '+ k); 
    }
    Public static void method2(){
    	integer l=1;
        System.debug('Test Class integer '+ l);
    }
}